language: php

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=master
  - CAKE_VERSION=2.6

before_script:
  - git clone --depth 1 --branch $CAKE_VERSION git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - rm -R app
  - git clone --depth 1 --branch master git://github.com/dereuromark/tools-app app
  - git clone --depth 1 --branch master git://github.com/dereuromark/tools plugins/Tools
  - cp -R ../cakephp-queue plugins/Queue
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - mkdir ./app/tmp
  - mkdir ./app/tmp/logs
  - mkdir ./app/tmp/queue
  - mkdir ./app/tmp/tests
  - mkdir ./app/tmp/cache
  - mkdir ./app/tmp/cache/persistent
  - mkdir ./app/tmp/cache/models
  - chmod -R 0777 ./app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    }" > app/Config/database.php
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then composer global require 'phpunit/phpunit=3.7.33'; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ./vendors/PHPUnit; fi"
  - cd app
script:
  - ../lib/Cake/Console/cake test Queue AllQueue --stderr

notifications:
  email: false
