language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - REPO_NAME=cakephp-queue
    - PLUGIN_NAME=Queue
    - REQUIRE=""

  matrix:
    - DB=mysql CAKE_VERSION=2.6
    - DB=mysql CAKE_VERSION=2.7

matrix:
  include:
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=2.6 COVERALLS=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - cd ../cakephp/app
  - composer require --dev --no-interaction --prefer-source dereuromark/cakephp-tools:0.*
  - echo "<?php App::uses('MyModel', 'Tools.Model'); class AppModel extends MyModel {}" > Model/AppModel.php
  - echo "<?php App::uses('MyController', 'Tools.Controller'); class AppController extends MyController {}" > Controller/AppController.php
  - echo "<?php App::uses('BaseEmailConfig', 'Tools.Config'); class EmailConfig extends BaseEmailConfig {}" > Config/email.php
  - echo "Configure::write('Security.salt', 'AycG93b0qyJfIxfs2guVoUubWwvniR2G0FgaC9mi');" >> Config/bootstrap.php
  - echo "Configure::write('Security.cipherSeed', '16659201697453542496749683615');" >> Config/bootstrap.php
  - cd ..

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
