language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.1
      env: DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'

    - php: 7.1
      env: DB=sqlite db_dsn='sqlite:///:memory:'

    - php: 5.6
      env: PREFER_LOWEST=1

    - php: 7.1
      env: CODECOVERAGE=1 DEFAULT=0

    - php: 7.1
      env: PHPCS=1 DEFAULT=0

before_script:
  - if [[ $PHPCS != 1 ]]; then composer require phpunit/phpunit:"^5.7.14|^6.0" ; fi

  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable ; fi

  - if [[ $DB == 'mysql' ]]; then mysql -u root -e 'CREATE DATABASE cakephp_test;' ; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres ; fi

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS == 1 ]]; then composer cs-check ; fi

  - if [[ $CODECOVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml || true; fi
  - if [[ $CODECOVERAGE == 1 ]]; then wget -O codecov.sh https://codecov.io/bash; fi
  - if [[ $CODECOVERAGE == 1 ]]; then bash codecov.sh; fi

notifications:
  email: false
